language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq git
script: python setup.py coverage
after_success:
    - pip install python-coveralls && coveralls
