language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq git
    - if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then pip install configparser --no-compile || true; fi
script: python setup.py coverage
after_success:
    - pip install coveralls && coveralls
